### PR TITLE
Fixed the support for test projects. Fixed tests also

### PR DESCRIPTION
**Pull request by SpartaDeveloper93**

### CODE REVIEW

**Comment by SpartaDeveloper93** [comment]
@matt-lethargic, I have raised this PR to fix existing issues

**Comment by matt-lethargic** [comment]
Hi @SpartaDeveloper93 thanks for the PR. What issues is this fixing?

**Comment by SpartaDeveloper93** [comment]
@matt-lethargic , I was looking for a GeoJSON library to use in our application and stumbled upon this project. I noticed that the last build failed, so I forked the repo.
When running the test cases locally, I noticed that one of the test cases is failing in the main branch: `Can_DeserializeGeneric` . I made the change in "Feature Collection" as that one had an Inconsistent modifier declaration. Also, TestProperties needs to be lowercase for JSON to deserialize to work. 
Also, changed csproj to just removed net462 and add netstandard 2.0 to make it consistent with main project.

**Comment by xfischer** [comment]
Thanks

**Pull request merged**
